# This file shows the expected format for secrets
# Copy this to .streamlit/secrets.toml and add your actual database URL

[connections.postgresql]
url = "your_postgresql_database_url_here"

# Alternative format:
# DATABASE_URL = "your_postgresql_database_url_here"